
version: '3'

services:
  web:
    build: .
    command: sh run.sh
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    environment:
      - DB_ENGINE='postgresql'
      - DB_HOST='localhost'
      - DB_PORT='5432'
      - DB_PASSWORD='pass'
      - DB_USER='Lukasz'
      - DB_NAME='database'

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - DB_ENGINE='postgresql'
      - DB_HOST='localhost'
      - DB_PORT='5432'
      - DB_PASSWORD='pass'
      - DB_USER='Lukasz'
      - DB_NAME='database'
    volumes:
      - ./postgres-data