version: '3'

services:
  web:
    build: .
    command: sh run.sh
    volumes:
      - .:/code
    environment:
      DB_ENGINE: "postgresql"
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
    ports:
      - "5000:5000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "testdb"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "app"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data



